### ISSUE TITLE
Find npm libs for console GUI

### ISSUE THREAD

**Issue by tshemsedinov** [HowProgrammingWorks/Labs#4]

**Comment by revan730** [comment]
We should take a look at this one: https://github.com/chjj/blessed .It`s curses-based, has a rich documentation and written completely in JS.

**Comment by fedirsmilianets** [comment]
Wow! curses reimplemented in JS. Sounds good.
I had a look on the docs. The default textarea has an interesting feature: 

> readEditor(callback) - Open text editor in $EDITOR, read the output from the resulting file. Takes a callback which receives the final value.

We can go with it, i think. Only problem is that we must ensure that our users will set a text editor they can live with.
