### ISSUE TITLE
Запуск тестов под windows

### ISSUE THREAD

**Issue by sirielua** [HowProgrammingWorks/Labs#9]
Здравствуйте. В целях самообучения решал ваши задачи. Тесты не запускались, так как в файле hpw.js жестко прописаны пути с прямыми слешами:
```
const curDir = process.cwd();
const dir = curDir + (curDir.includes('/Exercises') ? '' : '/Exercises');
```
У себя я заменил этот фрагмент кода на следующий:
```
const isWin = !!process.platform.match(/^win/);
const subdir = isWin ? '\\Exercises' : '/Exercises';
const dir = curDir + (curDir.includes(subdir) ? '' : subdir);
```
Так же я заменил команду для тестов nmp
```
eslint ./Exercises; hpw
```
на
```
eslint .\\Exercises && hpw
```

Можно ли отвязать тесты от папки /Exercises? Пробрасывать папку через параметр (прим. eslint .\\Exercises && hpw -path \path\to\my\files)?

Извините, если я пишу не так или не по адресу, только открываю для себя github и node

**Comment by tshemsedinov** [comment]
Привет! Поддержка виндовса не планируется, в качестве самообучения, для разработки установите себе Fedora 30 или любую другую приличную ОС.
Отмечу отдельно, что виндовс - это НЕ стыдно.
